### ISSUE TITLE
Support disable / unregister.

### ISSUE THREAD

**Issue by SamMousa** [mkraemer/react-pcntl#6]
Currently the constructor adds a timer to the event loop, but no reference to this timer is saved.

I'd like to be able to either destroy the `PCNTL` object or unregister it from the event loop.

A simple solution would be to store the result of `$loop->addPeriodicTimer` and implement a stop / start mechanism:

```
public function stop() {
    if (isset($this->timer) && $this->timer->isActive()) {
        $this->timer->cancel();
    }
}

public function start() {
    if (!isset($this->timer) || !$this->timer->isActive()) {
        $this->timer = $this->loop->addPeriodicTimer($this, $this->interval);
    }
}
```

I can make a PR if you want.

**Comment by mkraemer** [comment]
Sounds good!

Yes, a PR would be welcome for this :) Thanks

**Comment by nick4fake** [comment]
@mkraemer Please check latest pull request
